---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vfw-promtail
  namespace: vfw-promtail
data:
  promtail.yaml: |
    server:
      log_level: info
      log_format: logfmt
      http_listen_port: 3101
      #http_listen_port: 1514
      grpc_listen_port: 9080


    clients:
      - url: https://loki-gateway.observe.olsdemo.com/loki/api/v1/push  
        tenant_id: vfw-logging
        basic_auth:
          username: "your-username"
          password: "your-password"


    positions:
      filename: /run/promtail/positions.yaml

    scrape_configs:
    - job_name: vfw-syslog
      encoding: utf-8
      syslog:
        listen_address: 0.0.0.0:1514
        idle_timeout: 60s
        label_structured_data: yes
        labels:
          job: "vfw-syslog"
      relabel_configs:
        - source_labels: [__syslog_message_hostname]
          target_label: vfw_host
        - source_labels: [__syslog_message_hostname]
          target_label: vfw_hostname
        - source_labels: [__syslog_message_severity]
          target_label: vfw_level
        - source_labels: [__syslog_message_app_name]
          target_label: vfw_application
        - source_labels: [__syslog_message_facility]
          target_label: vfw_facility
        - source_labels: [__syslog_connection_hostname]
          target_label: vfw_connection_hostname
    #- job_name: syslog
    #  syslog:
    #    listen_address: 0.0.0.0:514
    #    idle_timeout: 60s
    #    label_structured_data: yes
    #    labels:
    #      job: "syslog"
    #  relabel_configs:
    #    - source_labels: ['__syslog_message_hostname']
    #      target_label: 'host'
    #  # Add an additional scrape config for OPNsense IDS alerts shipped over syslog
    #- job_name: syslog-ids
    #  syslog:
    #    listen_address: 0.0.0.0:1514
    #    idle_timeout: 60s
    #    label_structured_data: yes
    #    labels:
    #      job: "syslog-ids"
    #  relabel_configs:
    #    - source_labels: ['__syslog_message_hostname']
    #      target_label: 'host'
---
apiVersion: v1
kind: Service
metadata:
  name: vfw-promtail
  namespace: vfw-promtail
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
  selector:
    #app: minio
    app.kubernetes.io/instance: loki
---
apiVersion: v1
kind: Service
metadata:
  name: vfw-promtail-1514
  namespace: vfw-promtail
spec:
  type: NodePort
  ports:
  - port: 1514
    targetPort: 1514
  selector:
    app.kubernetes.io/instance: loki
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    meta.helm.sh/release-name: loki
    meta.helm.sh/release-namespace: loki-stack
  labels:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: promtail
    app.kubernetes.io/version: 2.8.3
    helm.sh/chart: promtail-6.13.1
  name: vfw-promtail
  namespace: vfw-promtail
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: promtail
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/instance: loki
        app.kubernetes.io/name: promtail
    spec:
      containers:
      - args:
        - -config.file=/etc/promtail/promtail.yaml
        env:
        - name: TZ
          value: "Asia/Bangkok"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: docker.io/grafana/promtail:2.8.3
        imagePullPolicy: IfNotPresent
        name: promtail
        ports:
        - containerPort: 3101
          name: http-metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /ready
            port: http-metrics
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/promtail
          name: config
        - mountPath: /run/promtail
          name: run
        - mountPath: /var/lib/docker/containers
          name: containers
          readOnly: true
        - mountPath: /var/log/pods
          name: pods
          readOnly: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      #serviceAccount: loki-promtail
      #serviceAccountName: loki-promtail
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      volumes:
      - name: config
        configMap:
          defaultMode: 420
          name: vfw-promtail
      - hostPath:
          path: /run/promtail
          type: ""
        name: run
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: containers
      - hostPath:
          path: /var/log/pods
          type: ""
        name: pods
