server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  #- url: http://localhost:3100/loki/api/v1/push
  - url: https://gateway-loki.milkyk8slab.dedyn.io/loki/api/v1/push


scrape_configs:
- job_name: vfw-syslog
  encoding: utf-8
  syslog:
    listen_address: 0.0.0.0:1514
    idle_timeout: 60s
    label_structured_data: yes
    labels:
      job: "vfw-syslog"
  relabel_configs:
    - source_labels: [__syslog_message_hostname]
      target_label: vfw_host
    - source_labels: [__syslog_message_hostname]
      target_label: vfw_hostname
    - source_labels: [__syslog_message_severity]
      target_label: vfw_level
    - source_labels: [__syslog_message_app_name]
      target_label: vfw_application
    - source_labels: [__syslog_message_facility]
      target_label: vfw_facility
    - source_labels: [__syslog_connection_hostname]
      target_label: vfw_connection_hostname
